remote_theme: pages-themes/tactile@v0.2.0

title: "Mansour Shahhosseini"
description: "PhD student • Quantitative Marketing & Econometrics • Research & Projects"

url: "https://mansourshahhosseini.github.io"
baseurl: ""  

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap   # auto-generate sitemap.xml
  - jekyll-seo-tag   # adds proper <meta> tags for Google
